export const vocabN5extra1 = [
  { title: "Sapaan & Ungkapan (Greetings)", items: [
    { jp: "おはようございます", ro: "ohayou gozaimasu", id: "Selamat pagi" },
    { jp: "こんにちは", ro: "konnichiwa", id: "Selamat siang" },
    { jp: "こんばんは", ro: "konbanwa", id: "Selamat malam" },
    { jp: "さようなら", ro: "sayounara", id: "Selamat tinggal" },
    { jp: "ありがとうございます", ro: "arigatou gozaimasu", id: "Terima kasih" },
    { jp: "すみません", ro: "sumimasen", id: "Permisi / Maaf" },
    { jp: "おねがいします", ro: "onegaishimasu", id: "Tolong / Mohon" },
    { jp: "いただきます", ro: "itadakimasu", id: "Selamat makan" },
    { jp: "ごちそうさま", ro: "gochisousama", id: "Terima kasih (makanan)" },
    { jp: "おやすみなさい", ro: "oyasuminasai", id: "Selamat tidur" }
  ]},
  { title: "Kata Tanya (Question Words)", items: [
    { jp: "なに", ro: "nani", id: "Apa" },
    { jp: "だれ", ro: "dare", id: "Siapa" },
    { jp: "どこ", ro: "doko", id: "Di mana" },
    { jp: "いつ", ro: "itsu", id: "Kapan" },
    { jp: "なぜ", ro: "naze", id: "Mengapa" },
    { jp: "どう", ro: "dou", id: "Bagaimana" },
    { jp: "いくら", ro: "ikura", id: "Berapa (harga)" },
    { jp: "いくつ", ro: "ikutsu", id: "Berapa (jumlah)" },
    { jp: "どれ", ro: "dore", id: "Yang mana" },
    { jp: "どちら", ro: "dochira", id: "Yang mana (2)" }
  ]},
  { title: "Posisi & Arah (Position)", items: [
    { jp: "うえ", ro: "ue", id: "Atas" },
    { jp: "した", ro: "shita", id: "Bawah" },
    { jp: "まえ", ro: "mae", id: "Depan" },
    { jp: "うしろ", ro: "ushiro", id: "Belakang" },
    { jp: "みぎ", ro: "migi", id: "Kanan" },
    { jp: "ひだり", ro: "hidari", id: "Kiri" },
    { jp: "なか", ro: "naka", id: "Dalam" },
    { jp: "そと", ro: "soto", id: "Luar" },
    { jp: "となり", ro: "tonari", id: "Sebelah" },
    { jp: "ちかく", ro: "chikaku", id: "Dekat" }
  ]},
  { title: "Waktu Lanjut (Time 2)", items: [
    { jp: "あさ", ro: "asa", id: "Pagi" },
    { jp: "ひる", ro: "hiru", id: "Siang" },
    { jp: "よる", ro: "yoru", id: "Malam" },
    { jp: "ゆうがた", ro: "yuugata", id: "Sore" },
    { jp: "まいしゅう", ro: "maishuu", id: "Setiap minggu" },
    { jp: "まいつき", ro: "maitsuki", id: "Setiap bulan" },
    { jp: "まいとし", ro: "maitoshi", id: "Setiap tahun" },
    { jp: "せんしゅう", ro: "senshuu", id: "Minggu lalu" },
    { jp: "らいしゅう", ro: "raishuu", id: "Minggu depan" },
    { jp: "ことし", ro: "kotoshi", id: "Tahun ini" }
  ]},
  { title: "Musim & Cuaca (Seasons)", items: [
    { jp: "はる", ro: "haru", id: "Musim semi" },
    { jp: "なつ", ro: "natsu", id: "Musim panas" },
    { jp: "あき", ro: "aki", id: "Musim gugur" },
    { jp: "ふゆ", ro: "fuyu", id: "Musim dingin" },
    { jp: "くもり", ro: "kumori", id: "Mendung" },
    { jp: "はれ", ro: "hare", id: "Cerah" },
    { jp: "たいふう", ro: "taifuu", id: "Topan" },
    { jp: "あたたかい", ro: "atatakai", id: "Hangat" },
    { jp: "すずしい", ro: "suzushii", id: "Sejuk" },
    { jp: "むしあつい", ro: "mushiatsui", id: "Gerah / Lembap" }
  ]},
  { title: "Alat Tulis & Kantor (Stationery)", items: [
    { jp: "かみ", ro: "kami", id: "Kertas" },
    { jp: "ペン", ro: "pen", id: "Pena" },
    { jp: "はさみ", ro: "hasami", id: "Gunting" },
    { jp: "のり", ro: "nori", id: "Lem" },
    { jp: "ものさし", ro: "monosashi", id: "Penggaris" },
    { jp: "ホッチキス", ro: "hotchikisu", id: "Stapler" },
    { jp: "ふうとう", ro: "fuutou", id: "Amplop" },
    { jp: "きって", ro: "kitte", id: "Perangko" },
    { jp: "はがき", ro: "hagaki", id: "Kartu pos" },
    { jp: "てがみ", ro: "tegami", id: "Surat" }
  ]},
  { title: "Buah-buahan (Fruits)", items: [
    { jp: "りんご", ro: "ringo", id: "Apel" },
    { jp: "バナナ", ro: "banana", id: "Pisang" },
    { jp: "みかん", ro: "mikan", id: "Jeruk mandarin" },
    { jp: "ぶどう", ro: "budou", id: "Anggur" },
    { jp: "いちご", ro: "ichigo", id: "Stroberi" },
    { jp: "すいか", ro: "suika", id: "Semangka" },
    { jp: "もも", ro: "momo", id: "Persik" },
    { jp: "レモン", ro: "remon", id: "Lemon" },
    { jp: "メロン", ro: "meron", id: "Melon" },
    { jp: "なし", ro: "nashi", id: "Pir Jepang" }
  ]},
  { title: "Minuman & Makanan 2 (Food 2)", items: [
    { jp: "コーヒー", ro: "ko-hi-", id: "Kopi" },
    { jp: "ジュース", ro: "ju-su", id: "Jus" },
    { jp: "ビール", ro: "bi-ru", id: "Bir" },
    { jp: "おさけ", ro: "osake", id: "Sake / Alkohol" },
    { jp: "ケーキ", ro: "ke-ki", id: "Kue" },
    { jp: "チョコレート", ro: "chokore-to", id: "Cokelat" },
    { jp: "おかし", ro: "okashi", id: "Camilan" },
    { jp: "サンドイッチ", ro: "sandoicchi", id: "Sandwich" },
    { jp: "カレー", ro: "kare-", id: "Kari" },
    { jp: "おべんとう", ro: "obentou", id: "Bekal makan" }
  ]},
  { title: "Kata Kerja Harian (Daily Verbs)", items: [
    { jp: "あらう", ro: "arau", id: "Mencuci" },
    { jp: "きる", ro: "kiru", id: "Memakai (baju)" },
    { jp: "ぬぐ", ro: "nugu", id: "Melepas (baju)" },
    { jp: "かける", ro: "kakeru", id: "Memakai (kacamata)" },
    { jp: "はく", ro: "haku", id: "Memakai (celana/sepatu)" },
    { jp: "かぶる", ro: "kaburu", id: "Memakai (topi)" },
    { jp: "とる", ro: "toru", id: "Mengambil" },
    { jp: "おく", ro: "oku", id: "Meletakkan" },
    { jp: "もつ", ro: "motsu", id: "Memegang / Membawa" },
    { jp: "つかう", ro: "tsukau", id: "Menggunakan" }
  ]},
  { title: "Kata Kerja Sosial (Social Verbs)", items: [
    { jp: "あげる", ro: "ageru", id: "Memberi" },
    { jp: "もらう", ro: "morau", id: "Menerima" },
    { jp: "くれる", ro: "kureru", id: "Memberi (ke saya)" },
    { jp: "てつだう", ro: "tetsudau", id: "Membantu" },
    { jp: "たのむ", ro: "tanomu", id: "Meminta tolong" },
    { jp: "こたえる", ro: "kotaeru", id: "Menjawab" },
    { jp: "しつもん", ro: "shitsumon", id: "Pertanyaan" },
    { jp: "でかける", ro: "dekakeru", id: "Pergi keluar" },
    { jp: "つれていく", ro: "tsureteiku", id: "Membawa (orang)" },
    { jp: "もっていく", ro: "motteiku", id: "Membawa (benda)" }
  ]},
  { title: "Kata Keterangan (Adverbs)", items: [
    { jp: "とても", ro: "totemo", id: "Sangat" },
    { jp: "すこし", ro: "sukoshi", id: "Sedikit" },
    { jp: "たくさん", ro: "takusan", id: "Banyak" },
    { jp: "いつも", ro: "itsumo", id: "Selalu" },
    { jp: "ときどき", ro: "tokidoki", id: "Kadang-kadang" },
    { jp: "よく", ro: "yoku", id: "Sering" },
    { jp: "まだ", ro: "mada", id: "Masih / Belum" },
    { jp: "もう", ro: "mou", id: "Sudah" },
    { jp: "たぶん", ro: "tabun", id: "Mungkin" },
    { jp: "ぜんぜん", ro: "zenzen", id: "Sama sekali tidak" }
  ]},
  { title: "Kata Keterangan 2 (Adverbs 2)", items: [
    { jp: "はじめて", ro: "hajimete", id: "Pertama kali" },
    { jp: "だんだん", ro: "dandan", id: "Pelan-pelan / Makin" },
    { jp: "すぐ", ro: "sugu", id: "Segera" },
    { jp: "ゆっくり", ro: "yukkuri", id: "Pelan-pelan" },
    { jp: "いっしょに", ro: "issho ni", id: "Bersama" },
    { jp: "ひとりで", ro: "hitori de", id: "Sendirian" },
    { jp: "もちろん", ro: "mochiron", id: "Tentu saja" },
    { jp: "けっして", ro: "kesshite", id: "Tidak pernah" },
    { jp: "たいてい", ro: "taitei", id: "Biasanya" },
    { jp: "ちょうど", ro: "choudo", id: "Tepat" }
  ]},
  { title: "Angka 2 & Penghitung (Counters)", items: [
    { jp: "ろく", ro: "roku", id: "Enam" },
    { jp: "しち", ro: "shichi", id: "Tujuh" },
    { jp: "はち", ro: "hachi", id: "Delapan" },
    { jp: "きゅう", ro: "kyuu", id: "Sembilan" },
    { jp: "じゅう", ro: "juu", id: "Sepuluh" },
    { jp: "ひゃく", ro: "hyaku", id: "Seratus" },
    { jp: "せん", ro: "sen", id: "Seribu" },
    { jp: "まん", ro: "man", id: "Sepuluh ribu" },
    { jp: "ひとつ", ro: "hitotsu", id: "Satu (umum)" },
    { jp: "ふたつ", ro: "futatsu", id: "Dua (umum)" }
  ]},
  { title: "Penghitung 2 (Counters 2)", items: [
    { jp: "みっつ", ro: "mittsu", id: "Tiga (umum)" },
    { jp: "よっつ", ro: "yottsu", id: "Empat (umum)" },
    { jp: "いつつ", ro: "itsutsu", id: "Lima (umum)" },
    { jp: "いっぽん", ro: "ippon", id: "Satu (panjang)" },
    { jp: "にほん", ro: "nihon", id: "Dua (panjang)" },
    { jp: "いちまい", ro: "ichimai", id: "Satu (lembar)" },
    { jp: "にまい", ro: "nimai", id: "Dua (lembar)" },
    { jp: "ひとり", ro: "hitori", id: "Satu orang" },
    { jp: "ふたり", ro: "futari", id: "Dua orang" },
    { jp: "いっさつ", ro: "issatsu", id: "Satu (buku)" }
  ]},
  { title: "Olahraga & Kegiatan (Sports)", items: [
    { jp: "サッカー", ro: "sakka-", id: "Sepak bola" },
    { jp: "やきゅう", ro: "yakyuu", id: "Bisbol" },
    { jp: "テニス", ro: "tenisu", id: "Tenis" },
    { jp: "すいえい", ro: "suiei", id: "Renang" },
    { jp: "ジョギング", ro: "jogingu", id: "Jogging" },
    { jp: "スキー", ro: "suki-", id: "Ski" },
    { jp: "ダンス", ro: "dansu", id: "Dansa" },
    { jp: "しあい", ro: "shiai", id: "Pertandingan" },
    { jp: "れんしゅう", ro: "renshuu", id: "Latihan" },
    { jp: "たいいく", ro: "taiiku", id: "Olahraga (pelajaran)" }
  ]},
  { title: "Benda Sehari-hari (Everyday Items)", items: [
    { jp: "さいふ", ro: "saifu", id: "Dompet" },
    { jp: "かぎ", ro: "kagi", id: "Kunci" },
    { jp: "ハンカチ", ro: "hankachi", id: "Sapu tangan" },
    { jp: "ティッシュ", ro: "tisshu", id: "Tisu" },
    { jp: "タオル", ro: "taoru", id: "Handuk" },
    { jp: "せっけん", ro: "sekken", id: "Sabun" },
    { jp: "はブラシ", ro: "haburashi", id: "Sikat gigi" },
    { jp: "くすり", ro: "kusuri", id: "Obat" },
    { jp: "おかね", ro: "okane", id: "Uang" },
    { jp: "でんわ", ro: "denwa", id: "Telepon" }
  ]},
  { title: "Kata Sifat Na (Na-Adjectives)", items: [
    { jp: "げんき", ro: "genki", id: "Sehat / Semangat" },
    { jp: "しずか", ro: "shizuka", id: "Tenang" },
    { jp: "にぎやか", ro: "nigiyaka", id: "Ramai" },
    { jp: "きれい", ro: "kirei", id: "Cantik / Bersih" },
    { jp: "ゆうめい", ro: "yuumei", id: "Terkenal" },
    { jp: "べんり", ro: "benri", id: "Praktis" },
    { jp: "たいへん", ro: "taihen", id: "Sulit / Berat" },
    { jp: "だいじょうぶ", ro: "daijoubu", id: "Tidak apa-apa" },
    { jp: "じょうず", ro: "jouzu", id: "Pandai" },
    { jp: "へた", ro: "heta", id: "Tidak pandai" }
  ]},
  { title: "Kata Sifat Na 2", items: [
    { jp: "すき", ro: "suki", id: "Suka" },
    { jp: "きらい", ro: "kirai", id: "Benci / Tidak suka" },
    { jp: "じょうぶ", ro: "joubu", id: "Kuat / Tahan lama" },
    { jp: "ひま", ro: "hima", id: "Senggang" },
    { jp: "かんたん", ro: "kantan", id: "Mudah / Simpel" },
    { jp: "だいじ", ro: "daiji", id: "Penting" },
    { jp: "いろいろ", ro: "iroiro", id: "Bermacam-macam" },
    { jp: "ハンサム", ro: "hansamu", id: "Tampan" },
    { jp: "しんせつ", ro: "shinsetsu", id: "Baik hati" },
    { jp: "ざんねん", ro: "zannen", id: "Sayang sekali" }
  ]},
  { title: "Partikel & Konjungsi (Particles)", items: [
    { jp: "しかし", ro: "shikashi", id: "Namun / Tetapi" },
    { jp: "そして", ro: "soshite", id: "Dan / Lalu" },
    { jp: "でも", ro: "demo", id: "Tapi" },
    { jp: "それから", ro: "sorekara", id: "Setelah itu" },
    { jp: "だから", ro: "dakara", id: "Karena itu" },
    { jp: "または", ro: "matawa", id: "Atau" },
    { jp: "それとも", ro: "soretomo", id: "Atau (pilihan)" },
    { jp: "けれども", ro: "keredomo", id: "Meskipun" },
    { jp: "つまり", ro: "tsumari", id: "Dengan kata lain" },
    { jp: "ところで", ro: "tokorode", id: "Ngomong-ngomong" }
  ]},
  { title: "Kata Kerja Gerakan (Movement)", items: [
    { jp: "のる", ro: "noru", id: "Naik (kendaraan)" },
    { jp: "おりる", ro: "oriru", id: "Turun (kendaraan)" },
    { jp: "わたる", ro: "wataru", id: "Menyeberang" },
    { jp: "まがる", ro: "magaru", id: "Berbelok" },
    { jp: "とまる", ro: "tomaru", id: "Berhenti" },
    { jp: "のぼる", ro: "noboru", id: "Mendaki / Naik" },
    { jp: "すわる", ro: "suwaru", id: "Duduk" },
    { jp: "たつ", ro: "tatsu", id: "Berdiri" },
    { jp: "はいる", ro: "hairu", id: "Masuk" },
    { jp: "でる", ro: "deru", id: "Keluar" }
  ]}
];
