export const vocabN5extra4 = [
  { title: "Tempat di Rumah 2 (House 2)", items: [
    { jp: "げんかん", ro: "genkan", id: "Pintu masuk rumah" },
    { jp: "ろうか", ro: "rouka", id: "Lorong" },
    { jp: "おしいれ", ro: "oshiire", id: "Lemari dinding" },
    { jp: "やね", ro: "yane", id: "Atap" },
    { jp: "にかい", ro: "nikai", id: "Lantai dua" },
    { jp: "いっかい", ro: "ikkai", id: "Lantai satu" },
    { jp: "ベランダ", ro: "beranda", id: "Balkon" },
    { jp: "ガレージ", ro: "gare-ji", id: "Garasi" },
    { jp: "へいわ", ro: "heiwa", id: "Pagar" },
    { jp: "ポスト", ro: "posuto", id: "Kotak surat" }
  ]},
  { title: "Cuaca & Bencana (Weather 2)", items: [
    { jp: "くもり", ro: "kumori", id: "Mendung" },
    { jp: "かみなり", ro: "kaminari", id: "Petir" },
    { jp: "にじ", ro: "niji", id: "Pelangi" },
    { jp: "きり", ro: "kiri", id: "Kabut" },
    { jp: "こおり", ro: "koori", id: "Es" },
    { jp: "つゆ", ro: "tsuyu", id: "Musim hujan" },
    { jp: "きおん", ro: "kion", id: "Suhu" },
    { jp: "てんきよほう", ro: "tenkiyohou", id: "Ramalan cuaca" },
    { jp: "じしん", ro: "jishin", id: "Gempa bumi" },
    { jp: "たいふう", ro: "taifuu", id: "Topan" }
  ]},
  { title: "Keperluan Mandi (Bath Items)", items: [
    { jp: "せっけん", ro: "sekken", id: "Sabun" },
    { jp: "シャンプー", ro: "shanpu-", id: "Sampo" },
    { jp: "タオル", ro: "taoru", id: "Handuk" },
    { jp: "ドライヤー", ro: "doraiya-", id: "Pengering rambut" },
    { jp: "くし", ro: "kushi", id: "Sisir" },
    { jp: "かがみ", ro: "kagami", id: "Cermin" },
    { jp: "はみがきこ", ro: "hamigakiko", id: "Pasta gigi" },
    { jp: "はブラシ", ro: "haburashi", id: "Sikat gigi" },
    { jp: "バスタオル", ro: "basutaoru", id: "Handuk mandi" },
    { jp: "おゆ", ro: "oyu", id: "Air panas" }
  ]},
  { title: "Keluarga 2 (Extended Family)", items: [
    { jp: "おじいさん", ro: "ojiisan", id: "Kakek" },
    { jp: "おばあさん", ro: "obaasan", id: "Nenek" },
    { jp: "おじさん", ro: "ojisan", id: "Paman" },
    { jp: "おばさん", ro: "obasan", id: "Bibi" },
    { jp: "いとこ", ro: "itoko", id: "Sepupu" },
    { jp: "むすこ", ro: "musuko", id: "Anak laki-laki (sendiri)" },
    { jp: "むすめ", ro: "musume", id: "Anak perempuan (sendiri)" },
    { jp: "おっと", ro: "otto", id: "Suami (sendiri)" },
    { jp: "つま", ro: "tsuma", id: "Istri (sendiri)" },
    { jp: "ごしゅじん", ro: "goshujin", id: "Suami (orang lain)" }
  ]},
  { title: "Hewan 2 (Animals 2)", items: [
    { jp: "ひつじ", ro: "hitsuji", id: "Domba" },
    { jp: "やぎ", ro: "yagi", id: "Kambing" },
    { jp: "にわとり", ro: "niwatori", id: "Ayam" },
    { jp: "ペット", ro: "petto", id: "Hewan peliharaan" },
    { jp: "かめ", ro: "kame", id: "Kura-kura" },
    { jp: "へび", ro: "hebi", id: "Ular" },
    { jp: "きんぎょ", ro: "kingyo", id: "Ikan mas" },
    { jp: "うさぎ", ro: "usagi", id: "Kelinci" },
    { jp: "ハムスター", ro: "hamusuta-", id: "Hamster" },
    { jp: "ライオン", ro: "raion", id: "Singa" }
  ]},
  { title: "Kata Kerja Penting (Essential Verbs)", items: [
    { jp: "おぼえる", ro: "oboeru", id: "Mengingat" },
    { jp: "わすれる", ro: "wasureru", id: "Lupa" },
    { jp: "なくす", ro: "nakusu", id: "Kehilangan" },
    { jp: "さわる", ro: "sawaru", id: "Menyentuh" },
    { jp: "こたえる", ro: "kotaeru", id: "Menjawab" },
    { jp: "はじめる", ro: "hajimeru", id: "Memulai" },
    { jp: "おわる", ro: "owaru", id: "Selesai" },
    { jp: "かわる", ro: "kawaru", id: "Berubah" },
    { jp: "なる", ro: "naru", id: "Menjadi" },
    { jp: "できる", ro: "dekiru", id: "Bisa / Jadi" }
  ]},
  { title: "Kata Kerja Penting 2 (Essential Verbs 2)", items: [
    { jp: "おくれる", ro: "okureru", id: "Terlambat" },
    { jp: "まにあう", ro: "maniau", id: "Tepat waktu" },
    { jp: "なおす", ro: "naosu", id: "Memperbaiki" },
    { jp: "こわれる", ro: "kowareru", id: "Rusak" },
    { jp: "おちる", ro: "ochiru", id: "Jatuh" },
    { jp: "あがる", ro: "agaru", id: "Naik" },
    { jp: "さがる", ro: "sagaru", id: "Turun" },
    { jp: "ふえる", ro: "fueru", id: "Bertambah" },
    { jp: "へる", ro: "heru", id: "Berkurang" },
    { jp: "かわく", ro: "kawaku", id: "Kering" }
  ]},
  { title: "Ungkapan Penting (Key Expressions)", items: [
    { jp: "はい", ro: "hai", id: "Ya" },
    { jp: "いいえ", ro: "iie", id: "Tidak" },
    { jp: "そうです", ro: "sou desu", id: "Benar" },
    { jp: "ちがいます", ro: "chigaimasu", id: "Salah / Beda" },
    { jp: "わかりました", ro: "wakarimashita", id: "Mengerti" },
    { jp: "しりません", ro: "shirimasen", id: "Tidak tahu" },
    { jp: "ちょっと", ro: "chotto", id: "Sedikit / Sebentar" },
    { jp: "どうぞ", ro: "douzo", id: "Silakan" },
    { jp: "だいじょうぶ", ro: "daijoubu", id: "Tidak apa-apa" },
    { jp: "おめでとう", ro: "omedetou", id: "Selamat" }
  ]},
  { title: "Sifat Orang (People Traits)", items: [
    { jp: "あかるい", ro: "akarui", id: "Ceria / Terang" },
    { jp: "くらい", ro: "kurai", id: "Gelap / Murung" },
    { jp: "まじめ", ro: "majime", id: "Serius / Rajin" },
    { jp: "やさしい", ro: "yasashii", id: "Baik hati" },
    { jp: "つよい", ro: "tsuyoi", id: "Kuat" },
    { jp: "よわい", ro: "yowai", id: "Lemah" },
    { jp: "わかい", ro: "wakai", id: "Muda" },
    { jp: "うるさい", ro: "urusai", id: "Berisik" },
    { jp: "しずか", ro: "shizuka", id: "Pendiam" },
    { jp: "おとなしい", ro: "otonashii", id: "Kalem / Tenang" }
  ]},
  { title: "Nomor Telepon & Alamat (Address)", items: [
    { jp: "じゅうしょ", ro: "juusho", id: "Alamat" },
    { jp: "でんわばんごう", ro: "denwabangou", id: "Nomor telepon" },
    { jp: "メールアドレス", ro: "me-ruadoresu", id: "Alamat email" },
    { jp: "ゆうびんばんごう", ro: "yuubinbangou", id: "Kode pos" },
    { jp: "なまえ", ro: "namae", id: "Nama" },
    { jp: "せい", ro: "sei", id: "Nama keluarga" },
    { jp: "めい", ro: "mei", id: "Nama depan" },
    { jp: "ねんれい", ro: "nenrei", id: "Umur" },
    { jp: "せいべつ", ro: "seibetsu", id: "Jenis kelamin" },
    { jp: "こくせき", ro: "kokuseki", id: "Kewarganegaraan" }
  ]},
  { title: "Akhiran & Sufiks (Counters 3)", items: [
    { jp: "いっぱい", ro: "ippai", id: "Satu gelas" },
    { jp: "にはい", ro: "nihai", id: "Dua gelas" },
    { jp: "いっかい", ro: "ikkai", id: "Satu kali" },
    { jp: "にかい", ro: "nikai", id: "Dua kali" },
    { jp: "いちだい", ro: "ichidai", id: "Satu unit (mesin)" },
    { jp: "いっこ", ro: "ikko", id: "Satu buah (kecil)" },
    { jp: "にこ", ro: "niko", id: "Dua buah (kecil)" },
    { jp: "いちど", ro: "ichido", id: "Sekali" },
    { jp: "にど", ro: "nido", id: "Dua kali" },
    { jp: "さんにん", ro: "sannin", id: "Tiga orang" }
  ]},
  { title: "Dunia Digital (Digital World)", items: [
    { jp: "けいたいでんわ", ro: "keitaidenwa", id: "Telepon genggam" },
    { jp: "スマホ", ro: "sumaho", id: "Smartphone" },
    { jp: "アプリ", ro: "apuri", id: "Aplikasi" },
    { jp: "インターネット", ro: "inta-netto", id: "Internet" },
    { jp: "ウェブサイト", ro: "webusaito", id: "Website" },
    { jp: "パスワード", ro: "pasuwa-do", id: "Password" },
    { jp: "メッセージ", ro: "messe-ji", id: "Pesan" },
    { jp: "しゃしん", ro: "shashin", id: "Foto" },
    { jp: "どうが", ro: "douga", id: "Video" },
    { jp: "けんさく", ro: "kensaku", id: "Pencarian" }
  ]},
  { title: "Liburan & Event (Holidays)", items: [
    { jp: "やすみ", ro: "yasumi", id: "Libur" },
    { jp: "なつやすみ", ro: "natsuyasumi", id: "Libur musim panas" },
    { jp: "ふゆやすみ", ro: "fuyuyasumi", id: "Libur musim dingin" },
    { jp: "おしょうがつ", ro: "oshougatsu", id: "Tahun baru" },
    { jp: "クリスマス", ro: "kurisumasu", id: "Natal" },
    { jp: "はなみ", ro: "hanami", id: "Melihat bunga sakura" },
    { jp: "おぼん", ro: "obon", id: "Festival Obon" },
    { jp: "たなばた", ro: "tanabata", id: "Festival Tanabata" },
    { jp: "ひなまつり", ro: "hinamatsuri", id: "Festival Boneka" },
    { jp: "こどものひ", ro: "kodomo no hi", id: "Hari Anak" }
  ]},
  { title: "Uang & Belanja (Money)", items: [
    { jp: "えん", ro: "en", id: "Yen" },
    { jp: "おかね", ro: "okane", id: "Uang" },
    { jp: "おつり", ro: "otsuri", id: "Kembalian" },
    { jp: "レシート", ro: "reshi-to", id: "Struk" },
    { jp: "きっぷ", ro: "kippu", id: "Tiket" },
    { jp: "ただ", ro: "tada", id: "Gratis" },
    { jp: "たかい", ro: "takai", id: "Mahal" },
    { jp: "やすい", ro: "yasui", id: "Murah" },
    { jp: "はらう", ro: "harau", id: "Membayar" },
    { jp: "かう", ro: "kau", id: "Membeli" }
  ]}
];
