export const vocabN5extra3 = [
  { title: "Perlengkapan Dapur (Kitchen Tools)", items: [
    { jp: "フライパン", ro: "furaipan", id: "Wajan" },
    { jp: "やかん", ro: "yakan", id: "Teko" },
    { jp: "おわん", ro: "owan", id: "Mangkuk" },
    { jp: "さら", ro: "sara", id: "Piring" },
    { jp: "ちゃわん", ro: "chawan", id: "Mangkuk nasi" },
    { jp: "はし", ro: "hashi", id: "Sumpit" },
    { jp: "スプーン", ro: "supu-n", id: "Sendok" },
    { jp: "フォーク", ro: "fo-ku", id: "Garpu" },
    { jp: "ナイフ", ro: "naifu", id: "Pisau" },
    { jp: "コップ", ro: "koppu", id: "Gelas" }
  ]},
  { title: "Bumbu & Rasa (Seasoning & Taste)", items: [
    { jp: "しお", ro: "shio", id: "Garam" },
    { jp: "さとう", ro: "satou", id: "Gula" },
    { jp: "す", ro: "su", id: "Cuka" },
    { jp: "あまい", ro: "amai", id: "Manis" },
    { jp: "からい", ro: "karai", id: "Pedas" },
    { jp: "しょっぱい", ro: "shoppai", id: "Asin" },
    { jp: "すっぱい", ro: "suppai", id: "Asam" },
    { jp: "にがい", ro: "nigai", id: "Pahit" },
    { jp: "あじ", ro: "aji", id: "Rasa" },
    { jp: "こしょう", ro: "koshou", id: "Merica" }
  ]},
  { title: "Sayuran (Vegetables)", items: [
    { jp: "にんじん", ro: "ninjin", id: "Wortel" },
    { jp: "たまねぎ", ro: "tamanegi", id: "Bawang bombay" },
    { jp: "じゃがいも", ro: "jagaimo", id: "Kentang" },
    { jp: "トマト", ro: "tomato", id: "Tomat" },
    { jp: "キャベツ", ro: "kyabetsu", id: "Kol" },
    { jp: "レタス", ro: "retasu", id: "Selada" },
    { jp: "きゅうり", ro: "kyuuri", id: "Timun" },
    { jp: "なす", ro: "nasu", id: "Terong" },
    { jp: "ピーマン", ro: "pi-man", id: "Paprika" },
    { jp: "だいこん", ro: "daikon", id: "Lobak" }
  ]},
  { title: "Daging & Protein (Meat & Protein)", items: [
    { jp: "ぎゅうにく", ro: "gyuuniku", id: "Daging sapi" },
    { jp: "ぶたにく", ro: "butaniku", id: "Daging babi" },
    { jp: "とりにく", ro: "toriniku", id: "Daging ayam" },
    { jp: "えび", ro: "ebi", id: "Udang" },
    { jp: "いか", ro: "ika", id: "Cumi-cumi" },
    { jp: "たこ", ro: "tako", id: "Gurita" },
    { jp: "かに", ro: "kani", id: "Kepiting" },
    { jp: "ハム", ro: "hamu", id: "Ham" },
    { jp: "ソーセージ", ro: "so-se-ji", id: "Sosis" },
    { jp: "チーズ", ro: "chi-zu", id: "Keju" }
  ]},
  { title: "Toko & Jual Beli (Shopping)", items: [
    { jp: "スーパー", ro: "su-pa-", id: "Supermarket" },
    { jp: "コンビニ", ro: "konbini", id: "Minimarket" },
    { jp: "パンや", ro: "pan ya", id: "Toko roti" },
    { jp: "はなや", ro: "hana ya", id: "Toko bunga" },
    { jp: "ほんや", ro: "hon ya", id: "Toko buku" },
    { jp: "くつや", ro: "kutsu ya", id: "Toko sepatu" },
    { jp: "くすりや", ro: "kusuri ya", id: "Apotek" },
    { jp: "にくや", ro: "niku ya", id: "Toko daging" },
    { jp: "さかなや", ro: "sakana ya", id: "Toko ikan" },
    { jp: "やおや", ro: "yaoya", id: "Toko sayur" }
  ]},
  { title: "Di Dalam Kota (In Town)", items: [
    { jp: "こうさてん", ro: "kousaten", id: "Persimpangan" },
    { jp: "しんごう", ro: "shingou", id: "Lampu lalu lintas" },
    { jp: "はし", ro: "hashi", id: "Jembatan" },
    { jp: "かど", ro: "kado", id: "Sudut / Pojok" },
    { jp: "どうろ", ro: "douro", id: "Jalan raya" },
    { jp: "ちゅうしゃじょう", ro: "chuushajou", id: "Tempat parkir" },
    { jp: "バスてい", ro: "basu tei", id: "Halte bus" },
    { jp: "こうばん", ro: "kouban", id: "Pos polisi" },
    { jp: "いりぐち", ro: "iriguchi", id: "Pintu masuk" },
    { jp: "でぐち", ro: "deguchi", id: "Pintu keluar" }
  ]},
  { title: "Kata Kerja Rumah (Home Verbs)", items: [
    { jp: "つくる", ro: "tsukuru", id: "Membuat" },
    { jp: "きる", ro: "kiru", id: "Memotong" },
    { jp: "にる", ro: "niru", id: "Merebus" },
    { jp: "やく", ro: "yaku", id: "Membakar / Memanggang" },
    { jp: "あたためる", ro: "atatameru", id: "Menghangatkan" },
    { jp: "ほす", ro: "hosu", id: "Menjemur" },
    { jp: "かたづける", ro: "katazukeru", id: "Merapikan" },
    { jp: "すてる", ro: "suteru", id: "Membuang" },
    { jp: "ひく", ro: "hiku", id: "Menarik" },
    { jp: "おす", ro: "osu", id: "Mendorong / Menekan" }
  ]},
  { title: "Kata Kerja Komunikasi (Communication)", items: [
    { jp: "いう", ro: "iu", id: "Berkata" },
    { jp: "おもう", ro: "omou", id: "Berpikir" },
    { jp: "しる", ro: "shiru", id: "Mengetahui" },
    { jp: "かんがえる", ro: "kangaeru", id: "Memikirkan" },
    { jp: "きめる", ro: "kimeru", id: "Memutuskan" },
    { jp: "えらぶ", ro: "erabu", id: "Memilih" },
    { jp: "しらべる", ro: "shiraberu", id: "Memeriksa" },
    { jp: "くらべる", ro: "kuraberu", id: "Membandingkan" },
    { jp: "つたえる", ro: "tsutaeru", id: "Menyampaikan" },
    { jp: "さそう", ro: "sasou", id: "Mengajak" }
  ]},
  { title: "Kegiatan Rekreasi (Recreation)", items: [
    { jp: "りょこう", ro: "ryokou", id: "Perjalanan" },
    { jp: "キャンプ", ro: "kyanpu", id: "Kemah" },
    { jp: "ハイキング", ro: "haikingu", id: "Hiking" },
    { jp: "ピクニック", ro: "pikunikku", id: "Piknik" },
    { jp: "つり", ro: "tsuri", id: "Memancing" },
    { jp: "スポーツ", ro: "supo-tsu", id: "Olahraga" },
    { jp: "ゲーム", ro: "ge-mu", id: "Game" },
    { jp: "えをかく", ro: "e wo kaku", id: "Menggambar" },
    { jp: "うたをうたう", ro: "uta wo utau", id: "Menyanyi" },
    { jp: "ピアノ", ro: "piano", id: "Piano" }
  ]},
  { title: "Rumah Sakit (Hospital)", items: [
    { jp: "びょういん", ro: "byouin", id: "Rumah sakit" },
    { jp: "いしゃ", ro: "isha", id: "Dokter" },
    { jp: "かんごし", ro: "kangoshi", id: "Perawat" },
    { jp: "はいしゃ", ro: "haisha", id: "Dokter gigi" },
    { jp: "くすり", ro: "kusuri", id: "Obat" },
    { jp: "ちゅうしゃ", ro: "chuusha", id: "Suntikan" },
    { jp: "ねつ", ro: "netsu", id: "Demam" },
    { jp: "かぜ", ro: "kaze", id: "Flu / Pilek" },
    { jp: "せき", ro: "seki", id: "Batuk" },
    { jp: "あたまがいたい", ro: "atama ga itai", id: "Sakit kepala" }
  ]},
  { title: "Sifat Benda (Object Properties)", items: [
    { jp: "おもい", ro: "omoi", id: "Berat" },
    { jp: "かるい", ro: "karui", id: "Ringan" },
    { jp: "あつい", ro: "atsui", id: "Tebal" },
    { jp: "うすい", ro: "usui", id: "Tipis" },
    { jp: "かたい", ro: "katai", id: "Keras" },
    { jp: "やわらかい", ro: "yawarakai", id: "Lunak" },
    { jp: "まるい", ro: "marui", id: "Bulat" },
    { jp: "しかくい", ro: "shikakui", id: "Persegi" },
    { jp: "ほそい", ro: "hosoi", id: "Tipis / Kurus" },
    { jp: "ふとい", ro: "futoi", id: "Tebal / Gemuk" }
  ]},
  { title: "Ukuran & Jumlah (Size & Amount)", items: [
    { jp: "おおい", ro: "ooi", id: "Banyak" },
    { jp: "すくない", ro: "sukunai", id: "Sedikit" },
    { jp: "ひろい", ro: "hiroi", id: "Luas" },
    { jp: "せまい", ro: "semai", id: "Sempit" },
    { jp: "ふかい", ro: "fukai", id: "Dalam" },
    { jp: "あさい", ro: "asai", id: "Dangkal" },
    { jp: "とおい", ro: "tooi", id: "Jauh" },
    { jp: "ちかい", ro: "chikai", id: "Dekat" },
    { jp: "ぜんぶ", ro: "zenbu", id: "Semua" },
    { jp: "はんぶん", ro: "hanbun", id: "Setengah" }
  ]},
  { title: "Kegiatan Sehari (Daily Activities)", items: [
    { jp: "おきる", ro: "okiru", id: "Bangun" },
    { jp: "ねる", ro: "neru", id: "Tidur" },
    { jp: "あるく", ro: "aruku", id: "Berjalan" },
    { jp: "はしる", ro: "hashiru", id: "Berlari" },
    { jp: "およぐ", ro: "oyogu", id: "Berenang" },
    { jp: "のぼる", ro: "noboru", id: "Mendaki" },
    { jp: "あびる", ro: "abiru", id: "Mandi (shower)" },
    { jp: "みがく", ro: "migaku", id: "Menyikat" },
    { jp: "きがえる", ro: "kigaeru", id: "Berganti baju" },
    { jp: "でかける", ro: "dekakeru", id: "Pergi keluar" }
  ]},
  { title: "Pendidikan 2 (Education 2)", items: [
    { jp: "こたえ", ro: "kotae", id: "Jawaban" },
    { jp: "もんだい", ro: "mondai", id: "Soal / Masalah" },
    { jp: "れい", ro: "rei", id: "Contoh" },
    { jp: "いみ", ro: "imi", id: "Arti" },
    { jp: "ぶん", ro: "bun", id: "Kalimat" },
    { jp: "ことば", ro: "kotoba", id: "Kata" },
    { jp: "べんきょう", ro: "benkyou", id: "Belajar" },
    { jp: "れんしゅう", ro: "renshuu", id: "Latihan" },
    { jp: "テスト", ro: "tesuto", id: "Tes" },
    { jp: "クラス", ro: "kurasu", id: "Kelas" }
  ]},
  { title: "Satuan Waktu (Time Units)", items: [
    { jp: "びょう", ro: "byou", id: "Detik" },
    { jp: "ふん", ro: "fun", id: "Menit" },
    { jp: "じかん", ro: "jikan", id: "Jam (durasi)" },
    { jp: "にち", ro: "nichi", id: "Hari" },
    { jp: "しゅう", ro: "shuu", id: "Minggu" },
    { jp: "つき", ro: "tsuki", id: "Bulan" },
    { jp: "とし", ro: "toshi", id: "Tahun" },
    { jp: "おととい", ro: "ototoi", id: "Kemarin lusa" },
    { jp: "あさって", ro: "asatte", id: "Lusa" },
    { jp: "きょねん", ro: "kyonen", id: "Tahun lalu" }
  ]},
  { title: "Kata Penunjuk (Demonstratives)", items: [
    { jp: "これ", ro: "kore", id: "Ini (benda)" },
    { jp: "それ", ro: "sore", id: "Itu (benda)" },
    { jp: "あれ", ro: "are", id: "Itu jauh (benda)" },
    { jp: "ここ", ro: "koko", id: "Di sini" },
    { jp: "そこ", ro: "soko", id: "Di situ" },
    { jp: "あそこ", ro: "asoko", id: "Di sana" },
    { jp: "この", ro: "kono", id: "... ini" },
    { jp: "その", ro: "sono", id: "... itu" },
    { jp: "あの", ro: "ano", id: "... itu (jauh)" },
    { jp: "どの", ro: "dono", id: "... yang mana" }
  ]},
  { title: "Panggilan & Sebutan (Titles)", items: [
    { jp: "さん", ro: "san", id: "Pak/Bu/Sdr (sopan)" },
    { jp: "くん", ro: "kun", id: "Sebutan untuk laki-laki muda" },
    { jp: "ちゃん", ro: "chan", id: "Sebutan akrab/anak" },
    { jp: "さま", ro: "sama", id: "Sebutan sangat sopan" },
    { jp: "おとな", ro: "otona", id: "Orang dewasa" },
    { jp: "こども", ro: "kodomo", id: "Anak-anak" },
    { jp: "あかちゃん", ro: "akachan", id: "Bayi" },
    { jp: "おとこのこ", ro: "otoko no ko", id: "Anak laki-laki" },
    { jp: "おんなのこ", ro: "onna no ko", id: "Anak perempuan" },
    { jp: "おとこのひと", ro: "otoko no hito", id: "Laki-laki" }
  ]}
];
