export const vocabN4 = [
  { title: "Perasaan (Feelings)", items: [
    { jp: "うれしい", ro: "ureshii", id: "Senang" },
    { jp: "かなしい", ro: "kanashii", id: "Sedih" },
    { jp: "こわい", ro: "kowai", id: "Takut / Menakutkan" },
    { jp: "さびしい", ro: "sabishii", id: "Kesepian" },
    { jp: "はずかしい", ro: "hazukashii", id: "Malu" },
    { jp: "くやしい", ro: "kuyashii", id: "Kesal / Menyesal" },
    { jp: "うらやましい", ro: "urayamashii", id: "Iri" },
    { jp: "きもち", ro: "kimochi", id: "Perasaan" },
    { jp: "しんぱい", ro: "shinpai", id: "Khawatir" },
    { jp: "あんしん", ro: "anshin", id: "Lega / Tenang" }
  ]},
  { title: "Pekerjaan (Occupation)", items: [
    { jp: "いしゃ", ro: "isha", id: "Dokter" },
    { jp: "かんごし", ro: "kangoshi", id: "Perawat" },
    { jp: "けいさつかん", ro: "keisatsukan", id: "Polisi" },
    { jp: "うんてんしゅ", ro: "untenshu", id: "Sopir" },
    { jp: "りょうりにん", ro: "ryourinin", id: "Koki" },
    { jp: "エンジニア", ro: "enjinia", id: "Insinyur" },
    { jp: "べんごし", ro: "bengoshi", id: "Pengacara" },
    { jp: "かしゅ", ro: "kashu", id: "Penyanyi" },
    { jp: "しゃちょう", ro: "shachou", id: "Direktur" },
    { jp: "てんいん", ro: "ten'in", id: "Pelayan toko" }
  ]},
  { title: "Kesehatan (Health)", items: [
    { jp: "びょうき", ro: "byouki", id: "Sakit / Penyakit" },
    { jp: "かぜ", ro: "kaze", id: "Masuk angin" },
    { jp: "ねつ", ro: "netsu", id: "Demam" },
    { jp: "くすり", ro: "kusuri", id: "Obat" },
    { jp: "けが", ro: "kega", id: "Luka / Cedera" },
    { jp: "いたい", ro: "itai", id: "Sakit (rasa)" },
    { jp: "げんき", ro: "genki", id: "Sehat / Semangat" },
    { jp: "たいいん", ro: "taiin", id: "Keluar RS" },
    { jp: "にゅういん", ro: "nyuuin", id: "Masuk RS" },
    { jp: "けんこう", ro: "kenkou", id: "Kesehatan" }
  ]},
  { title: "Belanja (Shopping)", items: [
    { jp: "ねだん", ro: "nedan", id: "Harga" },
    { jp: "おつり", ro: "otsuri", id: "Kembalian" },
    { jp: "レジ", ro: "reji", id: "Kasir" },
    { jp: "セール", ro: "se-ru", id: "Diskon" },
    { jp: "にもつ", ro: "nimotsu", id: "Barang bawaan" },
    { jp: "ふくろ", ro: "fukuro", id: "Kantong / Tas" },
    { jp: "おみやげ", ro: "omiyage", id: "Oleh-oleh" },
    { jp: "クレジットカード", ro: "kurejittoka-do", id: "Kartu kredit" },
    { jp: "りょうしゅうしょ", ro: "ryoushuusho", id: "Kwitansi" },
    { jp: "うりば", ro: "uriba", id: "Konter penjualan" }
  ]},
  { title: "Perjalanan (Travel)", items: [
    { jp: "りょこう", ro: "ryokou", id: "Perjalanan" },
    { jp: "パスポート", ro: "pasupo-to", id: "Paspor" },
    { jp: "よやく", ro: "yoyaku", id: "Reservasi" },
    { jp: "ちず", ro: "chizu", id: "Peta" },
    { jp: "かんこう", ro: "kankou", id: "Wisata" },
    { jp: "くうこう", ro: "kuukou", id: "Bandara" },
    { jp: "しゅっぱつ", ro: "shuppatsu", id: "Keberangkatan" },
    { jp: "とうちゃく", ro: "touchaku", id: "Kedatangan" },
    { jp: "にもつ", ro: "nimotsu", id: "Bagasi" },
    { jp: "おみやげ", ro: "omiyage", id: "Suvenir" }
  ]},
  { title: "Hobi (Hobbies)", items: [
    { jp: "しゅみ", ro: "shumi", id: "Hobi" },
    { jp: "りょうり", ro: "ryouri", id: "Memasak" },
    { jp: "さんぽ", ro: "sanpo", id: "Jalan-jalan" },
    { jp: "うんどう", ro: "undou", id: "Olahraga" },
    { jp: "えいが", ro: "eiga", id: "Film" },
    { jp: "おんがく", ro: "ongaku", id: "Musik" },
    { jp: "しゃしん", ro: "shashin", id: "Fotografi" },
    { jp: "どくしょ", ro: "dokusho", id: "Membaca buku" },
    { jp: "つり", ro: "tsuri", id: "Memancing" },
    { jp: "カラオケ", ro: "karaoke", id: "Karaoke" }
  ]},
  { title: "Komputer & Teknologi (Tech)", items: [
    { jp: "パソコン", ro: "pasokon", id: "Komputer" },
    { jp: "インターネット", ro: "inta-netto", id: "Internet" },
    { jp: "メール", ro: "me-ru", id: "Email" },
    { jp: "けいたい", ro: "keitai", id: "HP" },
    { jp: "でんげん", ro: "dengen", id: "Daya / Power" },
    { jp: "ボタン", ro: "botan", id: "Tombol" },
    { jp: "がめん", ro: "gamen", id: "Layar" },
    { jp: "でんち", ro: "denchi", id: "Baterai" },
    { jp: "コンセント", ro: "konsento", id: "Stop kontak" },
    { jp: "プリンター", ro: "purinta-", id: "Printer" }
  ]},
  { title: "Kata Kerja N4 - 1", items: [
    { jp: "つかう", ro: "tsukau", id: "Menggunakan" },
    { jp: "おくる", ro: "okuru", id: "Mengirim" },
    { jp: "もらう", ro: "morau", id: "Menerima" },
    { jp: "あげる", ro: "ageru", id: "Memberi" },
    { jp: "かりる", ro: "kariru", id: "Meminjam" },
    { jp: "かえす", ro: "kaesu", id: "Mengembalikan" },
    { jp: "さがす", ro: "sagasu", id: "Mencari" },
    { jp: "みつける", ro: "mitsukeru", id: "Menemukan" },
    { jp: "なおす", ro: "naosu", id: "Memperbaiki" },
    { jp: "こわす", ro: "kowasu", id: "Merusak" }
  ]},
  { title: "Kata Kerja N4 - 2", items: [
    { jp: "きめる", ro: "kimeru", id: "Memutuskan" },
    { jp: "つたえる", ro: "tsutaeru", id: "Menyampaikan" },
    { jp: "よぶ", ro: "yobu", id: "Memanggil" },
    { jp: "わすれる", ro: "wasureru", id: "Lupa" },
    { jp: "おぼえる", ro: "oboeru", id: "Mengingat" },
    { jp: "しらべる", ro: "shiraberu", id: "Menyelidiki" },
    { jp: "かんがえる", ro: "kangaeru", id: "Berpikir" },
    { jp: "きをつける", ro: "ki wo tsukeru", id: "Berhati-hati" },
    { jp: "やめる", ro: "yameru", id: "Berhenti" },
    { jp: "つづける", ro: "tsuzukeru", id: "Melanjutkan" }
  ]},
  { title: "Kata Sifat N4", items: [
    { jp: "べんり", ro: "benri", id: "Praktis" },
    { jp: "ふべん", ro: "fuben", id: "Tidak praktis" },
    { jp: "しずか", ro: "shizuka", id: "Tenang" },
    { jp: "にぎやか", ro: "nigiyaka", id: "Ramai" },
    { jp: "きれい", ro: "kirei", id: "Cantik / Bersih" },
    { jp: "きたない", ro: "kitanai", id: "Kotor" },
    { jp: "ていねい", ro: "teinei", id: "Sopan" },
    { jp: "ひつよう", ro: "hitsuyou", id: "Perlu" },
    { jp: "かんたん", ro: "kantan", id: "Mudah" },
    { jp: "ふくざつ", ro: "fukuzatsu", id: "Rumit" }
  ]},
  { title: "Masyarakat (Society)", items: [
    { jp: "せいかつ", ro: "seikatsu", id: "Kehidupan" },
    { jp: "せかい", ro: "sekai", id: "Dunia" },
    { jp: "しゃかい", ro: "shakai", id: "Masyarakat" },
    { jp: "けいざい", ro: "keizai", id: "Ekonomi" },
    { jp: "せいじ", ro: "seiji", id: "Politik" },
    { jp: "ニュース", ro: "nyu-su", id: "Berita" },
    { jp: "じこ", ro: "jiko", id: "Kecelakaan" },
    { jp: "じしん", ro: "jishin", id: "Gempa bumi" },
    { jp: "かじ", ro: "kaji", id: "Kebakaran" },
    { jp: "こうつう", ro: "koutsuu", id: "Lalu lintas" }
  ]},
  { title: "Pendidikan (Education)", items: [
    { jp: "そつぎょう", ro: "sotsugyou", id: "Lulus" },
    { jp: "にゅうがく", ro: "nyuugaku", id: "Masuk sekolah" },
    { jp: "じゅぎょう", ro: "jugyou", id: "Pelajaran" },
    { jp: "せいせき", ro: "seiseki", id: "Nilai" },
    { jp: "れきし", ro: "rekishi", id: "Sejarah" },
    { jp: "すうがく", ro: "suugaku", id: "Matematika" },
    { jp: "かがく", ro: "kagaku", id: "Sains" },
    { jp: "ぶんか", ro: "bunka", id: "Budaya" },
    { jp: "けいけん", ro: "keiken", id: "Pengalaman" },
    { jp: "きょういく", ro: "kyouiku", id: "Pendidikan" }
  ]}
];
